server:
  port: 8082
  error:
    include-message: on-param
    whitelabel:
      enabled: false
    servlet:
      context-path: /api/v1/core

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/refook_core
    driver-class-name: org.postgresql.Driver
    username: superrefook
    password: refookapp
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update

refook:
  ru:
    core:
      jwtCookieName: refook_security
      jwtSecret: refookJWTSecretKey
      jwtExpirationMs: 86400000
# logging:
#   file:
#     name: core.log
