server:
  port: 8082
  error:
    include-message: on-param
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/refook_core
    driver-class-name: org.postgresql.Driver
    username: superrefook
    password: refookapp
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
  kafka:
    # Перечисляем всех наших брокеров
    bootstrap-servers: kafka:29092
    producer:
      # Настраиваем сериализацию сообщений
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    view-topic: view
logging:
  file:
    path: ./core/log/dev/
    name: ${logging.file.path}core.log
