server:
  port: 8082
  error:
    include-message: on-param
    whitelabel:
      enabled: false
    servlet:
      context-path: /api/v1/core

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/refook_core
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: psql
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
# KeyCloak
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8090/realms/SpringBootExample
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/SpringBootExample

refook:
  ru:
    core:
      jwtCookieName: refook_security
      jwtSecret: refookJWTSecretKey
      jwtExpirationMs: 86400000
logging:
  file:
    path: ./core/log/dev/
    name: ${logging.file.path}core.log
