server:
  port: 8082
  error:
    include-message: on-param
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
  kafka:
    # Перечисляем всех наших брокеров
    bootstrap-servers: host.docker.internal:29092
    producer:
      # Настраиваем сериализацию сообщений
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  file:
    path: ./core/log/dev/
    name: ${logging.file.path}core.log
