server:
  port: 8000

ru:
  refook:
    uri:
      security: http://security.refook.ru:8081
      core: http://core.refook.ru:8082
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8080/realms/SpringBootExample
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBootExample
          jwk-set-uri: http://localhost:8080/realms/SpringBootExample/protocol/openid-connect/certs
